on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy-to-s3:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build
        working-directory: vacs-map-app
        run: |
          npm install && npm run build-staging
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy to S3
        working-directory: vacs-map-app
        run: |
          aws s3 sync dist s3://stories2.theplotline.org/vacs/ --delete
